# Generated by Django 5.1.3 on 2024-11-22 11:40

import user.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, error_messages={'unique': 'This contact number is already in use.'}, max_length=20, null=True, validators=[user.utils.validate_contact_number], verbose_name='contact number'),
        ),
    ]
